name: Deploy To Github Pages

on:
  push:
    branches:
      - master
  repository_dispatch:
    types:
      - start

jobs:
  deploy:
    name: Deploy markdown To Pages
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai

    steps:
      - name: Checkout Repository master branch
        uses: actions/checkout@master

      - name: Setup Node.js 10.x
        uses: actions/setup-node@master
        with:
          node-version: "10.x"

      - name: Sync yuque Files
        env:
          YUQUE_TOKEN: ${{ secrets.YUQUE_TOKEN }}
        run: |
          npm install
          npm run start
          # 插件会拉取知识库下所有的文档，此命令是过滤出API文档的md文件，其他文件删除
          find docs/* ! -name "VDPRO3*.md" -type f -print -exec rm -rf {} \;

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # deploy_key: ${{ secrets.SSH_PRIVATE_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: master
          publish_dir: ./docs
          destination_dir: ./docs
